spring.application.name=LuxuryPC

# PostgreSQL Supabase
#spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.fxwmcnagogiwczmyfmnu&password=trangwebpcuytin
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?user=postgres.fxwmcnagogiwczmyfmnu&password=trangwebpcuytin&prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=10

# Server
server.port=8080