user_updates_raw = """
UPDATE products SET brand = N'Intel', description = N'TDP: 125W | 24 Cores, up to 6.0GHz, LGA 1700' WHERE id = 1;
UPDATE products SET brand = N'AMD', description = N'TDP: 170W | 16 Cores, 128MB L3 Cache, AM5' WHERE id = 2;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W | 20 Cores, Hybrid Architecture' WHERE id = 3;
UPDATE products SET brand = N'AMD', description = N'TDP: 120W | Best gaming CPU, 8 Cores, 3D V-Cache' WHERE id = 4;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W | 14 Cores, Mid-range gaming' WHERE id = 5;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | 6 Cores, Zen 4 Architecture, AM5' WHERE id = 6;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W | Special Edition, 6.0GHz' WHERE id = 7;
UPDATE products SET brand = N'AMD', description = N'TDP: 170W | 12 Cores, 5.6GHz Boost' WHERE id = 8;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W | 16 Cores, No Integrated Graphics' WHERE id = 9;
UPDATE products SET brand = N'AMD', description = N'TDP: 120W | Legendary AM4 gaming CPU' WHERE id = 10;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W | Budget King, 6 Cores' WHERE id = 11;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | Integrated Vega Graphics' WHERE id = 12;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W | Entry level 14th Gen' WHERE id = 13;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | Budget 4 Cores, AM4' WHERE id = 14;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W | 16 Cores, Previous Flagship' WHERE id = 15;
UPDATE products SET brand = N'Xigmatek', description = N'TDP: 0W' WHERE id = 16;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W | 10 Cores, Efficient Gaming' WHERE id = 17;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | AI Engine, Radeon 760M' WHERE id = 18;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W | 12 Cores, LGA 1700' WHERE id = 19;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | 8 Cores, Low Power 65W' WHERE id = 20;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W | Old Gen Budget King' WHERE id = 21;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | Super Budget 6 Cores' WHERE id = 22;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W | Legacy Flagship LGA 1200' WHERE id = 23;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | Popular AM4 CPU' WHERE id = 24;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W | Stable and Cheap' WHERE id = 25;
UPDATE products SET brand = N'AMD', description = N'TDP: 105W | 12 Cores, Workstation' WHERE id = 26;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W | Office work, 2 Cores' WHERE id = 27;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | Ultra Budget Graphics' WHERE id = 28;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W | High Clock Legacy' WHERE id = 29;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | Powerful APU, Radeon 780M' WHERE id = 30;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 450W | Ultimate Gaming GPU' WHERE id = 31;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 320W | High-end 4K Gaming' WHERE id = 32;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 285W | Perfect for 2K Gaming' WHERE id = 33;
UPDATE products SET brand = N'AMD', description = N'TDP: 320W | AMD Flagship, 24GB' WHERE id = 34;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 160W | Efficient 1080p/2K' WHERE id = 35;
UPDATE products SET brand = N'AMD', description = N'TDP: 220W | Best value 2K GPU' WHERE id = 36;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 115W | Popular Mid-range' WHERE id = 37;
UPDATE products SET brand = N'AMD', description = N'TDP: 75W | Best budget 1080p' WHERE id = 38;
UPDATE products SET brand = N'ASUS', description = N'TDP: 450W | Premium build cooling' WHERE id = 39;
UPDATE products SET brand = N'MSI', description = N'TDP: 200W | Quiet and Cool' WHERE id = 40;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 115W | Triple Fan Budget' WHERE id = 41;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 220W | 12GB GDDR6X, Fast' WHERE id = 42;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | Budget RDNA 3' WHERE id = 43;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 75W | Entry level RTX' WHERE id = 44;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 115W | Compact dual fan' WHERE id = 45;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 200W | Pink Edition RGB' WHERE id = 46;
UPDATE products SET brand = N'ASUS', description = N'TDP: 285W | Rugged build quality' WHERE id = 47;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 320W | High performance legacy' WHERE id = 48;
UPDATE products SET brand = N'Sapphire', description = N'TDP: 220W | Golden Rabbit Edition' WHERE id = 49;
UPDATE products SET brand = N'PowerColor', description = N'TDP: 220W | Excellent cooling' WHERE id = 50;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 75W | No external power' WHERE id = 51;
UPDATE products SET brand = N'AMD', description = N'TDP: 115W | Great 1440p value' WHERE id = 52;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 320W | LCD screen on GPU' WHERE id = 53;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 140W | Workstation GPU' WHERE id = 54;
UPDATE products SET brand = N'AMD', description = N'TDP: 140W | Professional Graphics' WHERE id = 55;
UPDATE products SET brand = N'Intel', description = N'TDP: 225W | Intel High-end GPU' WHERE id = 56;
UPDATE products SET brand = N'Intel', description = N'TDP: 225W | Budget King Intel' WHERE id = 57;
UPDATE products SET brand = N'ASUS', description = N'TDP: 200W | Clean white build' WHERE id = 58;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 450W | Massive cooler' WHERE id = 59;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 115W | Small and efficient' WHERE id = 60;
UPDATE products SET brand = N'Corsair', description = N'TDP: 10W | DDR5 6000MHz Black' WHERE id = 61;
UPDATE products SET brand = N'G.Skill', description = N'TDP: 15W | DDR5 6400MHz RGB' WHERE id = 62;
UPDATE products SET brand = N'Kingston', description = N'TDP: 5W | DDR4 3200MHz' WHERE id = 63;
UPDATE products SET brand = N'TeamGroup', description = N'TDP: 5W | DDR5 6000MHz White' WHERE id = 64;
UPDATE products SET brand = N'ADATA', description = N'TDP: 5W | DDR5 5200MHz' WHERE id = 65;
UPDATE products SET brand = N'Crucial', description = N'TDP: 5W | Standard office RAM' WHERE id = 66;
UPDATE products SET brand = N'Corsair', description = N'TDP: 15W | DDR5 7200MHz' WHERE id = 67;
UPDATE products SET brand = N'G.Skill', description = N'TDP: 10W | DDR4 3600MHz' WHERE id = 68;
UPDATE products SET brand = N'Lexar', description = N'TDP: 0W | DDR4 3200MHz Budget' WHERE id = 69;
UPDATE products SET brand = N'Kingston', description = N'TDP: 15W | DDR5 7200MHz' WHERE id = 70;
UPDATE products SET brand = N'PNY', description = N'TDP: 5W | DDR4 3200MHz RGB' WHERE id = 71;
UPDATE products SET brand = N'Silicon Power', description = N'TDP: 5W | Value RAM 3200' WHERE id = 72;
UPDATE products SET brand = N'Mushkin', description = N'TDP: 5W | DDR5 5600MHz' WHERE id = 73;
UPDATE products SET brand = N'Razer', description = N'TDP: 5W | DDR4 4000MHz' WHERE id = 74;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W | DDR5 4800MHz OEM' WHERE id = 75;
UPDATE products SET brand = N'Thermaltake', description = N'TDP: 5W | DDR4 3600MHz RGB' WHERE id = 76;
UPDATE products SET brand = N'Zadak', description = N'TDP: 5W | DDR5 6000MHz' WHERE id = 77;
UPDATE products SET brand = N'Acer', description = N'TDP: 5W | Budget Gaming RAM' WHERE id = 78;
UPDATE products SET brand = N'GeIL', description = N'TDP: 5W | DDR4 3200MHz' WHERE id = 79;
UPDATE products SET brand = N'V-Color', description = N'TDP: 5W | DDR4 3600MHz RGB' WHERE id = 80;
UPDATE products SET brand = N'Kingston', description = N'TDP: 5W | DDR5 5600MHz Kit' WHERE id = 81;
UPDATE products SET brand = N'Corsair', description = N'TDP: 10W | DDR4 3200 Low Profile' WHERE id = 82;
UPDATE products SET brand = N'G.Skill', description = N'TDP: 5W | Optimized for Ryzen' WHERE id = 83;
UPDATE products SET brand = N'TeamGroup', description = N'TDP: 5W | DDR5 4800 Basic' WHERE id = 84;
UPDATE products SET brand = N'Crucial', description = N'TDP: 5W | 6000MHz Overclock' WHERE id = 85;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 5W | 3733MHz w/ Demo' WHERE id = 86;
UPDATE products SET brand = N'Lexar', description = N'TDP: 5W | DDR5 6400MHz' WHERE id = 87;
UPDATE products SET brand = N'Netac', description = N'TDP: 5W | Budget RGB RAM' WHERE id = 88;
UPDATE products SET brand = N'GALAX', description = N'TDP: 5W | 8000MHz White OC' WHERE id = 89;
UPDATE products SET brand = N'OLOy', description = N'TDP: 5W | DDR5 6000MHz Black' WHERE id = 90;
UPDATE products SET brand = N'ASUS', description = N'TDP: 50W | Flagship Intel Board' WHERE id = 91;
UPDATE products SET brand = N'MSI', description = N'TDP: 40W | Best Mid-range Intel' WHERE id = 92;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 50W | High perf Z790' WHERE id = 93;
UPDATE products SET brand = N'ASUS', description = N'TDP: 40W | Standard AM5 Board' WHERE id = 94;
UPDATE products SET brand = N'ASRock', description = N'TDP: 5W | Budget Intel 12/13' WHERE id = 95;
UPDATE products SET brand = N'MSI', description = N'TDP: 50W | High-end AM5' WHERE id = 96;
UPDATE products SET brand = N'ASUS', description = N'TDP: 0W | Office Intel Board' WHERE id = 97;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 30W | Legendary AM4 Budget' WHERE id = 98;
UPDATE products SET brand = N'ASUS', description = N'TDP: 40W | ITX Intel Board' WHERE id = 99;
UPDATE products SET brand = N'MSI', description = N'TDP: 50W | Ultimate Overclock' WHERE id = 100;
UPDATE products SET brand = N'ASRock', description = N'TDP: 50W | Gear design, E-ATX' WHERE id = 101;
UPDATE products SET brand = N'ASUS', description = N'TDP: 50W | For Creators' WHERE id = 102;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 40W | ITX AM5 Board' WHERE id = 103;
UPDATE products SET brand = N'MSI', description = N'TDP: 0W | Cheap office build' WHERE id = 104;
UPDATE products SET brand = N'ASUS', description = N'TDP: 50W | Best of AM5' WHERE id = 105;
UPDATE products SET brand = N'Biostar', description = N'TDP: 40W | Budget B760' WHERE id = 106;
UPDATE products SET brand = N'COLORFUL', description = N'TDP: 40W | White Motherboard' WHERE id = 107;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 30W | Budget AM4' WHERE id = 108;
UPDATE products SET brand = N'NZXT', description = N'TDP: 50W | Clean Aesthetic' WHERE id = 109;
UPDATE products SET brand = N'ASRock', description = N'TDP: 30W | Cheap AM5 entry' WHERE id = 110;
UPDATE products SET brand = N'EVGA', description = N'TDP: 50W | Limitless OC' WHERE id = 111;
UPDATE products SET brand = N'MSI', description = N'TDP: 40W | Silent AM4' WHERE id = 112;
UPDATE products SET brand = N'ASUS', description = N'TDP: 30W | Durable AM4' WHERE id = 113;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 50W | Basic Z790' WHERE id = 114;
UPDATE products SET brand = N'ASRock', description = N'TDP: 40W | Solid B550 AM4' WHERE id = 115;
UPDATE products SET brand = N'MSI', description = N'TDP: 40W | Budget AM5 WiFi' WHERE id = 116;
UPDATE products SET brand = N'ASUS', description = N'TDP: 50W | Mainstream Z790' WHERE id = 117;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 0W | LGA 1700 Office' WHERE id = 118;
UPDATE products SET brand = N'ASRock', description = N'TDP: 50W | White AM5 High' WHERE id = 119;
UPDATE products SET brand = N'Valkyrie', description = N'TDP: 50W | Biostar Flagship' WHERE id = 120;
UPDATE products SET brand = N'Samsung', description = N'TDP: 9W | NVMe Gen4 7450MB/s' WHERE id = 121;
UPDATE products SET brand = N'Samsung', description = N'TDP: 9W | NVMe Gen4 7000MB/s' WHERE id = 122;
UPDATE products SET brand = N'WD', description = N'TDP: 9W | Top gaming SSD' WHERE id = 123;
UPDATE products SET brand = N'Crucial', description = N'TDP: 5W | Budget Gen4' WHERE id = 124;
UPDATE products SET brand = N'Kingston', description = N'TDP: 5W | Entry NVMe' WHERE id = 125;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W | Best SATA SSD' WHERE id = 126;
UPDATE products SET brand = N'SK hynix', description = N'TDP: 5W | Super Fast Gen4' WHERE id = 127;
UPDATE products SET brand = N'Lexar', description = N'TDP: 5W | Value Gen4 7400' WHERE id = 128;
UPDATE products SET brand = N'Crucial', description = N'TDP: 14W | Gen5 11700MB/s' WHERE id = 129;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 14W | Gen5 w/ Heatsink' WHERE id = 130;
UPDATE products SET brand = N'TeamGroup', description = N'TDP: 5W | Budget NVMe' WHERE id = 131;
UPDATE products SET brand = N'ADATA', description = N'TDP: 5W | PS5 Gen4' WHERE id = 132;
UPDATE products SET brand = N'WD', description = N'TDP: 5W | Reliable Gen4' WHERE id = 133;
UPDATE products SET brand = N'Seagate', description = N'TDP: 5W | High endurance' WHERE id = 134;
UPDATE products SET brand = N'Sabrent', description = N'TDP: 5W | Huge capacity' WHERE id = 135;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W | Gen3 King' WHERE id = 136;
UPDATE products SET brand = N'PNY', description = N'TDP: 5W | Budget Gen4' WHERE id = 137;
UPDATE products SET brand = N'Silicon Power', description = N'TDP: 75W | Gen4 Value' WHERE id = 138;
UPDATE products SET brand = N'Corsair', description = N'TDP: 5W | Optimized for PS5' WHERE id = 139;
UPDATE products SET brand = N'Kingston', description = N'TDP: 9W | Fast Gen4 OS' WHERE id = 140;
UPDATE products SET brand = N'Crucial', description = N'TDP: 5W | SATA storage' WHERE id = 141;
UPDATE products SET brand = N'WD', description = N'TDP: 5W | Cheap upgrade' WHERE id = 142;
UPDATE products SET brand = N'MSI', description = N'TDP: 5W | High-end MSI SSD' WHERE id = 143;
UPDATE products SET brand = N'Transcend', description = N'TDP: 5W | Gen4 with Cache' WHERE id = 144;
UPDATE products SET brand = N'Razer', description = N'TDP: 5W | Dual heatsinks' WHERE id = 145;
UPDATE products SET brand = N'Lexar', description = N'TDP: 5W | Gen3 Budget' WHERE id = 146;
UPDATE products SET brand = N'Netac', description = N'TDP: 5W | Gen4 7000MB/s' WHERE id = 147;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W | Massive SATA' WHERE id = 148;
UPDATE products SET brand = N'ADATA', description = N'TDP: 12W | Cheapest SSD' WHERE id = 149;
UPDATE products SET brand = N'Crucial', description = N'TDP: 14W | Fastest Gen5' WHERE id = 150;
UPDATE products SET brand = N'LG', description = N'TDP: 5W | 27 OLED 240Hz' WHERE id = 151;
UPDATE products SET brand = N'Dell', description = N'TDP: 5W | 27" 4K IPS Black' WHERE id = 152;
UPDATE products SET brand = N'ASUS', description = N'TDP: 5W | 24 144Hz IPS' WHERE id = 153;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W | 32 4K 240Hz' WHERE id = 154;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 5W | 27 2K 170Hz' WHERE id = 155;
UPDATE products SET brand = N'AOC', description = N'TDP: 5W | Popular 144Hz' WHERE id = 156;
UPDATE products SET brand = N'ViewSonic', description = N'TDP: 5W | 27 165Hz IPS' WHERE id = 157;
UPDATE products SET brand = N'MSI', description = N'TDP: 5W | 2K Quantum Dot' WHERE id = 158;
UPDATE products SET brand = N'Dell', description = N'TDP: 5W | 34 QD-OLED' WHERE id = 159;
UPDATE products SET brand = N'BenQ', description = N'TDP: 5W | Pro Color Photo' WHERE id = 160;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W | 32 4K Smart' WHERE id = 161;
UPDATE products SET brand = N'LG', description = N'TDP: 5W | Budget 24 IPS' WHERE id = 162;
UPDATE products SET brand = N'ASUS', description = N'TDP: 5W | 42 OLED 4K' WHERE id = 163;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 5W | 24 180Hz OC' WHERE id = 164;
UPDATE products SET brand = N'HP', description = N'TDP: 5W | 4K Studio USB-C' WHERE id = 165;
UPDATE products SET brand = N'Acer', description = N'TDP: 5W | 27 2K 144Hz' WHERE id = 166;
UPDATE products SET brand = N'Dell', description = N'TDP: 5W | Fast IPS 165Hz' WHERE id = 167;
UPDATE products SET brand = N'LG', description = N'TDP: 5W | Square 16:18' WHERE id = 168;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W | 27 2K Curved' WHERE id = 169;
UPDATE products SET brand = N'Lenovo', description = N'TDP: 5W | 24.5 240Hz' WHERE id = 170;
UPDATE products SET brand = N'ASUS', description = N'TDP: 5W | Color Accurate' WHERE id = 171;
UPDATE products SET brand = N'HKC', description = N'TDP: 5W | Budget 2K Curved' WHERE id = 172;
UPDATE products SET brand = N'MSI', description = N'TDP: 5W | Budget 170Hz' WHERE id = 173;
UPDATE products SET brand = N'Dell', description = N'TDP: 5W | Office 22"' WHERE id = 174;
UPDATE products SET brand = N'LG', description = N'TDP: 5W | 29 UltraWide' WHERE id = 175;
UPDATE products SET brand = N'Philips', description = N'TDP: 0W | Budget 144Hz' WHERE id = 176;
UPDATE products SET brand = N'AOC', description = N'TDP: 5W | 34 UW 144Hz' WHERE id = 177;
UPDATE products SET brand = N'Corsair', description = N'TDP: 5W | Bendable OLED' WHERE id = 178;
UPDATE products SET brand = N'BenQ', description = N'TDP: 5W | Pro Esport 240Hz' WHERE id = 179;
UPDATE products SET brand = N'Xiaomi', description = N'TDP: 5W | 34 2K UltraWide' WHERE id = 180;
UPDATE products SET brand = N'Intel', description = N'TDP: 225W | 16GB GDDR6, 256-bit, 2100 MHz, 225W' WHERE id = 181;
UPDATE products SET brand = N'Intel', description = N'TDP: 225W | 8GB GDDR6, 256-bit, 2050 MHz, 225W' WHERE id = 182;
UPDATE products SET brand = N'Intel', description = N'TDP: 185W | 8GB GDDR6, 256-bit, 1700 MHz, 185W' WHERE id = 183;
UPDATE products SET brand = N'AMD', description = N'TDP: 285W | 20GB GDDR6, 80MB, 315W' WHERE id = 184;
UPDATE products SET brand = N'AMD', description = N'TDP: 220W | 16GB GDDR6, 64MB, 263W' WHERE id = 185;
UPDATE products SET brand = N'AMD', description = N'TDP: 65W | 6 Cores, 12 Threads, 35MB Cache, Up to 4.6GHz, Socket AM4' WHERE id = 186;
UPDATE products SET brand = N'ASUS', description = N'TDP: 50W | LGA1700, Intel Z790, 4x DDR5 (Up to 192GB), ATX' WHERE id = 187;
UPDATE products SET brand = N'ASUS', description = N'TDP: 50W | AM5, AMD X670E, PCIe 5.0, ATX' WHERE id = 188;
UPDATE products SET brand = N'ASUS', description = N'TDP: 450W | 24GB GDDR6X, 16384, PCIe 4.0' WHERE id = 189;
UPDATE products SET brand = N'ASUS', description = N'TDP: 0W | 32-inch, 3840x2160 (4K), 240Hz, QD-OLED' WHERE id = 190;
UPDATE products SET brand = N'ASUS', description = N'TDP: 15W | 360mm, Asetek 8th Gen, 3.5-inch Full Color' WHERE id = 191;
UPDATE products SET brand = N'ASUS', description = N'TDP: 0W | 1200W, 80 Plus Platinum, Full Modular, Real-time power draw' WHERE id = 192;
UPDATE products SET brand = N'MSI', description = N'TDP: 50W | LGA1700, Intel Z790, 7x M.2 slots, M-Vision Dashboard' WHERE id = 193;
UPDATE products SET brand = N'MSI', description = N'TDP: 40W | AM5, AMD B650, DDR5 7600+(OC), Realtek 2.5Gbps LAN' WHERE id = 194;
UPDATE products SET brand = N'MSI', description = N'TDP: 320W | 16GB GDDR6X, TRI FROZR 3, 2625 MHz' WHERE id = 195;
UPDATE products SET brand = N'MSI', description = N'TDP: 0W | 27-inch, 2560x1440 (2K), 360Hz, 0.03ms (GtG)' WHERE id = 196;
UPDATE products SET brand = N'MSI', description = N'TDP: 5W | ATX Full Tower, Curved Tempered Glass, Back-connect (Project Zero) support' WHERE id = 197;
UPDATE products SET brand = N'MSI', description = N'TDP: 15W | 360mm, ARGB Fans, Infinite Mirror IPS Style Design' WHERE id = 198;
UPDATE products SET brand = N'MSI', description = N'TDP: 14W | 2TB, Up to 12400 MB/s, Up to 11800 MB/s' WHERE id = 199;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 50W | LGA1700, 24+1+2 Phases, Wi-Fi 7, PCIe 5.0 x16' WHERE id = 200;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 50W | AM5, AMD X670E, 4x M.2 PCIe 5.0, Intel 2.5GbE LAN' WHERE id = 201;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 0W | 27-inch, Super Speed IPS, 2560x1440, 170Hz' WHERE id = 202;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 5W | 32-inch, OLED (QD-OLED), 3840x2160, DP 2.1 UHBR20 supported' WHERE id = 203;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 14W | PCIe 5.0 x4, NVMe 2.0, 12,400 MB/s, 11,800 MB/s' WHERE id = 204;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 0W | 1000W, PCIe Gen 5.0 (12VHPWR), 80 PLUS Gold' WHERE id = 205;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 0W | Mid Tower, 4mm Tempered Glass, Up to 420mm front' WHERE id = 206;
UPDATE products SET brand = N'Corsair', description = N'TDP: 15W | 32GB, 6000 MT/s, CL30, Intel XMP 3.0 / AMD EXPO' WHERE id = 207;
UPDATE products SET brand = N'Corsair', description = N'TDP: 65W | 64GB, 5600 MT/s, CL40' WHERE id = 208;
UPDATE products SET brand = N'Corsair', description = N'TDP: 5W | 360mm, 3x QX120 RGB Fans, 2.1-inch IPS Display, iCUE LINK Ecosystem' WHERE id = 209;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W | Mid-Tower, Black, RapidRoute System, Up to 10x 120mm fans' WHERE id = 210;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W | Dual Chamber Layout, Reverse-connector support, Front & Side Tempered Glass' WHERE id = 211;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W | 1000W, 80 PLUS Gold, Side-mounted modular connections, ATX 3.0 & PCIe 5.0 ready' WHERE id = 212;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W | 1600W, 80 PLUS Titanium, Gallium Nitride (GaN) FETs' WHERE id = 213;
UPDATE products SET brand = N'Corsair', description = N'TDP: 2W | Corsair OPX Optical-Mechanical, AXON 4000Hz Hyper-polling, iCUE Control Wheel' WHERE id = 214;
UPDATE products SET brand = N'Corsair', description = N'TDP: 1W | 15 programmable buttons, MARKSMAN 26K DPI Optical, SLIPSTREAM Wireless & Bluetooth' WHERE id = 215;
UPDATE products SET brand = N'Corsair', description = N'TDP: 1W | High-Density 50mm Neodymium, Spatial Dolby Atmos, Broadcast-grade detachable mic' WHERE id = 216;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W | 60 grams, HERO 2 Sensor (32,000 DPI), LIGHTFORCE Hybrid Switches, 4000Hz max polling' WHERE id = 217;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W | HERO 25K Sensor, 13 programmable controls, Dual-mode infinite scroll' WHERE id = 218;
UPDATE products SET brand = N'Logitech', description = N'TDP: 2W | Tenkeyless (TKL), Low Profile GL Tactile/Linear/Clicky, Up to 40 hours (100% brightness)' WHERE id = 219;
UPDATE products SET brand = N'Logitech', description = N'TDP: 2W | Dual-shot PBT keycaps, LIGHTSPEED Wireless, Bluetooth, USB, Dedicated volume roller and controls' WHERE id = 220;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W | 50mm Graphene Drivers, LIGHTSPEED, Bluetooth, 3.5mm wired, Up to 50 hours battery life' WHERE id = 221;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W | 8K DPI tracking on any surface, Quiet clicks technology, MagSpeed Electromagnetic scrolling' WHERE id = 222;
UPDATE products SET brand = N'Logitech', description = N'TDP: 2W | Spherically-dished Perfect Stroke keys, Smart illumination proximity sensor, Easy-Switch up to 3 devices' WHERE id = 223;
UPDATE products SET brand = N'Razer', description = N'TDP: 1W | 54 grams, Focus Pro 35K Optical Sensor Gen-2, True 8000Hz HyperPolling Wireless' WHERE id = 224;
UPDATE products SET brand = N'Razer', description = N'TDP: 1W | 63 grams, Right-handed ergonomic design, Focus Pro 30K Optical Sensor' WHERE id = 225;
UPDATE products SET brand = N'Razer', description = N'TDP: 2W | Razer Analog Optical Switches Gen-2, Rapid Trigger mode with adjustable actuation (0.1- 4.0mm), Dual-purpose digital dial' WHERE id = 226;
UPDATE products SET brand = N'Razer', description = N'TDP: 2W | Razer Green Clicky / Yellow Linear Switches, Per-key & 3-sided underglow RGB, 8 dedicated macro keys' WHERE id = 227;
UPDATE products SET brand = N'Razer', description = N'TDP: 1W | Razer HyperClear Super Wideband Mic, TriForce Titanium 50mm Drivers, Up to 70 hours' WHERE id = 228;
UPDATE products SET brand = N'Samsung', description = N'TDP: 9W | 2TB, Up to 7450 MB/s, Up to 6900 MB/s, Samsung Pascal Controller' WHERE id = 229;
UPDATE products SET brand = N'Samsung', description = N'TDP: 9W | 1TB, Up to 5000 MB/s, Up to 4200 MB/s' WHERE id = 230;
UPDATE products SET brand = N'Samsung', description = N'TDP: 9W | 2TB, USB 3.2 Gen 2 (10Gbps), IP65 water & dust resistant, 3-meter drop proof' WHERE id = 231;
UPDATE products SET brand = N'Samsung', description = N'TDP: 0W | 49-inch Curved Ultra-wide, 5120x1440 (Dual QHD), 240Hz, 0.03ms (GtG)' WHERE id = 232;
UPDATE products SET brand = N'Samsung', description = N'TDP: 0W | 55-inch 1000R Curved, 3840x2160 (4K), 165Hz, Yes, rotates vertically' WHERE id = 233;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W | Hi-Fi 24-bit Ultra High Quality Audio, Adaptive Noise Cancelling with Blade Lights, Stem style ergonomic fit' WHERE id = 234;
UPDATE products SET brand = N'Kingston', description = N'TDP: 15W | 32GB Kit, 7200 MT/s, CL38-44-44, 1.45V' WHERE id = 235;
UPDATE products SET brand = N'Kingston', description = N'TDP: 15W | 32GB Kit, 6000 MT/s, AMD EXPO / Intel XMP 3.0 certified' WHERE id = 236;
UPDATE products SET brand = N'Kingston', description = N'TDP: 9W | 2TB, Up to 7000 MB/s, Up to 7000 MB/s, Phison E18' WHERE id = 237;
UPDATE products SET brand = N'Kingston', description = N'TDP: 9W | 1TB, Up to 3500 MB/s, Up to 2100 MB/s, M.2 2280' WHERE id = 238;
UPDATE products SET brand = N'Kingston', description = N'TDP: 65W | Laptop Memory (SO-DIMM), 32GB Kit, 5600 MT/s' WHERE id = 239;
UPDATE products SET brand = N'WD', description = N'TDP: 5W | 12TB, 7200 RPM, 256MB, SATA 6 Gb/s' WHERE id = 240;
UPDATE products SET brand = N'Seagate', description = N'TDP: 7W | 16TB, 550TB/year, Rotational Vibration (RV) sensors' WHERE id = 241;
UPDATE products SET brand = N'Noctua', description = N'TDP: 5W | 2x NF-A15 HS-PWM fans, Full black design, Intel LGA1700/AM5 ready' WHERE id = 242;
UPDATE products SET brand = N'NZXT', description = N'TDP: 0W | Wrap-around tempered glass pane, 4x F120Q Airflow fans, Up to 435mm' WHERE id = 243;
UPDATE products SET brand = N'NZXT', description = N'TDP: 15W | 360mm aluminum radiator, 2.36-inch wide-angle TFT-LCD display, 640x640 pixels' WHERE id = 244;
UPDATE products SET brand = N'SteelSeries', description = N'TDP: 1W | Nova Pro Acoustic System, Active Noise Cancellation with Transparency Mode, Dual Battery Infinity System' WHERE id = 245;
UPDATE products SET brand = N'BenQ', description = N'TDP: 15W | 24.5-inch TN Panel, 360Hz, DyAc+ Technology motion blur reduction' WHERE id = 246;
UPDATE products SET brand = N'Sony', description = N'TDP: 1W | Integrated Processor V1 & HD Noise CancelingProcessor QN1, 8 microphones for extreme voice pick up, Up to 30 hours total life' WHERE id = 247;
UPDATE products SET brand = N'Crucial', description = N'TDP: 65W | 48GB Kit, 5600 MT/s, Low-profile aluminum black heatsink' WHERE id = 248;
UPDATE products SET brand = N'Fractal Design', description = N'TDP: 5W | Real walnut wood front panel struts, Mesh or Tempered Glass available, 2x Aspect 14 PWM fans' WHERE id = 249;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 0W | Dual-chamber adjustable ATX case, Two L-shaped diffuse LED RGB strips, Reversible design architecture' WHERE id = 250;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 4W | 120mm fans, Built-in 1.6-inch LCD screen on center fan, Daisy-chain interlocking mechanism' WHERE id = 251;
UPDATE products SET brand = N'EVGA', description = N'TDP: 0W | 1000W, 80 PLUS Gold Certified, Ultra-compact 130mm chassis size' WHERE id = 252;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 5W | Real-time temperature and usage status top screen, 2x FK120 fluid dynamic bearing fans, 6x 6mm copper heatpipes' WHERE id = 253;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 5W | Dual tower heatsink design, 2x TL-C12C 120mm PWM fans, 155mm standard height' WHERE id = 254;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W' WHERE id = 255;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 256;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W' WHERE id = 257;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W' WHERE id = 258;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 40W' WHERE id = 259;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 30W' WHERE id = 260;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 40W' WHERE id = 261;
UPDATE products SET brand = N'Kingmax', description = N'TDP: 10W' WHERE id = 262;
UPDATE products SET brand = N'KingSpec', description = N'TDP: 10W' WHERE id = 263;
UPDATE products SET brand = N'MSI', description = N'TDP: 250W' WHERE id = 264;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 300W' WHERE id = 265;
UPDATE products SET brand = N'MSI', description = N'TDP: 150W' WHERE id = 266;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 160W' WHERE id = 267;
UPDATE products SET brand = N'Kingston', description = N'TDP: 10W' WHERE id = 268;
UPDATE products SET brand = N'KingSpec', description = N'TDP: 10W' WHERE id = 269;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 270;
UPDATE products SET brand = N'Cooler Master', description = N'TDP: 0W' WHERE id = 271;
UPDATE products SET brand = N'FSP', description = N'TDP: 0W' WHERE id = 272;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 273;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 274;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 275;
UPDATE products SET brand = N'Corsair', description = N'TDP: 15W' WHERE id = 276;
UPDATE products SET brand = N'Cooler Master', description = N'TDP: 5W' WHERE id = 277;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 278;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 279;
UPDATE products SET brand = N'ASUS', description = N'TDP: 60W' WHERE id = 280;
UPDATE products SET brand = N'ASUS', description = N'TDP: 55W' WHERE id = 281;
UPDATE products SET brand = N'Corsair', description = N'TDP: 15W' WHERE id = 282;
UPDATE products SET brand = N'G.Skill', description = N'TDP: 15W' WHERE id = 283;
UPDATE products SET brand = N'ASUS', description = N'TDP: 450W' WHERE id = 284;
UPDATE products SET brand = N'Samsung', description = N'TDP: 15W' WHERE id = 285;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 286;
UPDATE products SET brand = N'SanDisk', description = N'TDP: 2W' WHERE id = 287;
UPDATE products SET brand = N'Samsung', description = N'TDP: 2W' WHERE id = 288;
UPDATE products SET brand = N'Lexar', description = N'TDP: 3W' WHERE id = 289;
UPDATE products SET brand = N'Kingston', description = N'TDP: 2W' WHERE id = 290;
UPDATE products SET brand = N'SanDisk', description = N'TDP: 1W' WHERE id = 291;
UPDATE products SET brand = N'Transcend', description = N'TDP: 2W' WHERE id = 292;
UPDATE products SET brand = N'ASUS', description = N'TDP: 3W' WHERE id = 293;
UPDATE products SET brand = N'Sony', description = N'TDP: 3W' WHERE id = 294;
UPDATE products SET brand = N'Kioxia', description = N'TDP: 2W' WHERE id = 295;
UPDATE products SET brand = N'TeamGroup', description = N'TDP: 2W' WHERE id = 296;
UPDATE products SET brand = N'SanDisk', description = N'TDP: 5W' WHERE id = 297;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W' WHERE id = 298;
UPDATE products SET brand = N'WD', description = N'TDP: 5W' WHERE id = 299;
UPDATE products SET brand = N'Crucial', description = N'TDP: 4W' WHERE id = 300;
UPDATE products SET brand = N'Seagate', description = N'TDP: 10W' WHERE id = 301;
UPDATE products SET brand = N'LaCie', description = N'TDP: 5W' WHERE id = 302;
UPDATE products SET brand = N'Kingston', description = N'TDP: 5W' WHERE id = 303;
UPDATE products SET brand = N'Transcend', description = N'TDP: 5W' WHERE id = 304;
UPDATE products SET brand = N'Corsair', description = N'TDP: 5W' WHERE id = 305;
UPDATE products SET brand = N'ADATA', description = N'TDP: 4W' WHERE id = 306;
UPDATE products SET brand = N'NZXT', description = N'TDP: 15W' WHERE id = 307;
UPDATE products SET brand = N'Corsair', description = N'TDP: 15W' WHERE id = 308;
UPDATE products SET brand = N'ASUS', description = N'TDP: 20W' WHERE id = 309;
UPDATE products SET brand = N'MSI', description = N'TDP: 12W' WHERE id = 310;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 15W' WHERE id = 311;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 15W' WHERE id = 312;
UPDATE products SET brand = N'Cooler Master', description = N'TDP: 12W' WHERE id = 313;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 10W' WHERE id = 314;
UPDATE products SET brand = N'Valkyrie', description = N'TDP: 15W' WHERE id = 315;
UPDATE products SET brand = N'ID-COOLING', description = N'TDP: 10W' WHERE id = 316;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 285W' WHERE id = 317;
UPDATE products SET brand = N'ASUS', description = N'TDP: 320W' WHERE id = 318;
UPDATE products SET brand = N'MSI', description = N'TDP: 165W' WHERE id = 319;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 220W' WHERE id = 320;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 285W' WHERE id = 321;
UPDATE products SET brand = N'AMD', description = N'TDP: 315W' WHERE id = 322;
UPDATE products SET brand = N'AMD', description = N'TDP: 263W' WHERE id = 323;
UPDATE products SET brand = N'AMD', description = N'TDP: 260W' WHERE id = 324;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 220W' WHERE id = 325;
UPDATE products SET brand = N'AMD', description = N'TDP: 245W' WHERE id = 326;
UPDATE products SET brand = N'Seagate', description = N'TDP: 6W' WHERE id = 327;
UPDATE products SET brand = N'WD', description = N'TDP: 6W' WHERE id = 328;
UPDATE products SET brand = N'Toshiba', description = N'TDP: 6W' WHERE id = 329;
UPDATE products SET brand = N'Seagate', description = N'TDP: 7W' WHERE id = 330;
UPDATE products SET brand = N'WD', description = N'TDP: 7W' WHERE id = 331;
UPDATE products SET brand = N'Seagate', description = N'TDP: 9W' WHERE id = 332;
UPDATE products SET brand = N'WD', description = N'TDP: 8W' WHERE id = 333;
UPDATE products SET brand = N'Toshiba', description = N'TDP: 8W' WHERE id = 334;
UPDATE products SET brand = N'WD', description = N'TDP: 7W' WHERE id = 335;
UPDATE products SET brand = N'Seagate', description = N'TDP: 6W' WHERE id = 336;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 337;
UPDATE products SET brand = N'MSI', description = N'TDP: 0W' WHERE id = 338;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 0W' WHERE id = 339;
UPDATE products SET brand = N'ASUS', description = N'TDP: 0W' WHERE id = 340;
UPDATE products SET brand = N'Cooler Master', description = N'TDP: 0W' WHERE id = 341;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 0W' WHERE id = 342;
UPDATE products SET brand = N'Super Flower', description = N'TDP: 0W' WHERE id = 343;
UPDATE products SET brand = N'Seasonic', description = N'TDP: 0W' WHERE id = 344;
UPDATE products SET brand = N'Logitech', description = N'TDP: 0W' WHERE id = 345;
UPDATE products SET brand = N'Thermaltake', description = N'TDP: 0W' WHERE id = 346;
UPDATE products SET brand = N'NZXT', description = N'TDP: 0W' WHERE id = 347;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 0W' WHERE id = 348;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 349;
UPDATE products SET brand = N'Montech', description = N'TDP: 0W' WHERE id = 350;
UPDATE products SET brand = N'HYTE', description = N'TDP: 0W' WHERE id = 351;
UPDATE products SET brand = N'Antec', description = N'TDP: 0W' WHERE id = 352;
UPDATE products SET brand = N'Fractal Design', description = N'TDP: 0W' WHERE id = 353;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 0W' WHERE id = 354;
UPDATE products SET brand = N'Xigmatek', description = N'TDP: 0W' WHERE id = 355;
UPDATE products SET brand = N'Phanteks', description = N'TDP: 0W' WHERE id = 356;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 5W' WHERE id = 357;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 4W' WHERE id = 358;
UPDATE products SET brand = N'Noctua', description = N'TDP: 5W' WHERE id = 359;
UPDATE products SET brand = N'ID-COOLING', description = N'TDP: 3W' WHERE id = 360;
UPDATE products SET brand = N'Cooler Master', description = N'TDP: 5W' WHERE id = 361;
UPDATE products SET brand = N'Jonsbo', description = N'TDP: 3W' WHERE id = 362;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 5W' WHERE id = 363;
UPDATE products SET brand = N'Be Quiet!', description = N'TDP: 5W' WHERE id = 364;
UPDATE products SET brand = N'PCCOOLER', description = N'TDP: 4W' WHERE id = 365;
UPDATE products SET brand = N'Valkyrie', description = N'TDP: 4W' WHERE id = 366;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 3W' WHERE id = 367;
UPDATE products SET brand = N'Corsair', description = N'TDP: 4W' WHERE id = 368;
UPDATE products SET brand = N'NZXT', description = N'TDP: 3W' WHERE id = 369;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 2W' WHERE id = 370;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 3W' WHERE id = 371;
UPDATE products SET brand = N'Phanteks', description = N'TDP: 3W' WHERE id = 372;
UPDATE products SET brand = N'ID-COOLING', description = N'TDP: 2W' WHERE id = 373;
UPDATE products SET brand = N'Cooler Master', description = N'TDP: 3W' WHERE id = 374;
UPDATE products SET brand = N'Antec', description = N'TDP: 2W' WHERE id = 375;
UPDATE products SET brand = N'Montech', description = N'TDP: 2W' WHERE id = 376;
UPDATE products SET brand = N'AKKO', description = N'TDP: 1W' WHERE id = 377;
UPDATE products SET brand = N'Keychron', description = N'TDP: 2W' WHERE id = 378;
UPDATE products SET brand = N'Royal Kludge', description = N'TDP: 1W' WHERE id = 379;
UPDATE products SET brand = N'FL-Esports', description = N'TDP: 2W' WHERE id = 380;
UPDATE products SET brand = N'MonsGeek', description = N'TDP: 2W' WHERE id = 381;
UPDATE products SET brand = N'EPOMAKER', description = N'TDP: 2W' WHERE id = 382;
UPDATE products SET brand = N'Ducky', description = N'TDP: 2W' WHERE id = 383;
UPDATE products SET brand = N'Varmilo', description = N'TDP: 1W' WHERE id = 384;
UPDATE products SET brand = N'NuPhy', description = N'TDP: 2W' WHERE id = 385;
UPDATE products SET brand = N'Womier', description = N'TDP: 1W' WHERE id = 386;
UPDATE products SET brand = N'Razer', description = N'TDP: 1W' WHERE id = 387;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W' WHERE id = 388;
UPDATE products SET brand = N'Pulsar', description = N'TDP: 1W' WHERE id = 389;
UPDATE products SET brand = N'Ninjutso', description = N'TDP: 1W' WHERE id = 390;
UPDATE products SET brand = N'LAMZU', description = N'TDP: 1W' WHERE id = 391;
UPDATE products SET brand = N'Endgame Gear', description = N'TDP: 1W' WHERE id = 392;
UPDATE products SET brand = N'VGN', description = N'TDP: 1W' WHERE id = 393;
UPDATE products SET brand = N'VXE', description = N'TDP: 1W' WHERE id = 394;
UPDATE products SET brand = N'SteelSeries', description = N'TDP: 1W' WHERE id = 395;
UPDATE products SET brand = N'ASUS', description = N'TDP: 1W' WHERE id = 396;
UPDATE products SET brand = N'HyperX', description = N'TDP: 1W' WHERE id = 397;
UPDATE products SET brand = N'Razer', description = N'TDP: 1W' WHERE id = 398;
UPDATE products SET brand = N'Corsair', description = N'TDP: 2W' WHERE id = 399;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W' WHERE id = 400;
UPDATE products SET brand = N'SteelSeries', description = N'TDP: 2W' WHERE id = 401;
UPDATE products SET brand = N'EPOS', description = N'TDP: 1W' WHERE id = 402;
UPDATE products SET brand = N'Audio-Technica', description = N'TDP: 1W' WHERE id = 403;
UPDATE products SET brand = N'JBL', description = N'TDP: 1W' WHERE id = 404;
UPDATE products SET brand = N'ASUS', description = N'TDP: 2W' WHERE id = 405;
UPDATE products SET brand = N'EKSA', description = N'TDP: 1W' WHERE id = 406;
UPDATE products SET brand = N'SanDisk', description = N'TDP: 1W' WHERE id = 407;
UPDATE products SET brand = N'SanDisk', description = N'TDP: 1W' WHERE id = 408;
UPDATE products SET brand = N'SanDisk', description = N'TDP: 2W' WHERE id = 409;
UPDATE products SET brand = N'Samsung', description = N'TDP: 1W' WHERE id = 410;
UPDATE products SET brand = N'Samsung', description = N'TDP: 2W' WHERE id = 411;
UPDATE products SET brand = N'Kingston', description = N'TDP: 1W' WHERE id = 412;
UPDATE products SET brand = N'Kingston', description = N'TDP: 2W' WHERE id = 413;
UPDATE products SET brand = N'Lexar', description = N'TDP: 3W' WHERE id = 414;
UPDATE products SET brand = N'Lexar', description = N'TDP: 2W' WHERE id = 415;
UPDATE products SET brand = N'Sony', description = N'TDP: 2W' WHERE id = 416;
UPDATE products SET brand = N'Sony', description = N'TDP: 3W' WHERE id = 417;
UPDATE products SET brand = N'Kioxia', description = N'TDP: 2W' WHERE id = 418;
UPDATE products SET brand = N'Transcend', description = N'TDP: 3W' WHERE id = 419;
UPDATE products SET brand = N'TeamGroup', description = N'TDP: 2W' WHERE id = 420;
UPDATE products SET brand = N'ASUS', description = N'TDP: 3W' WHERE id = 421;
UPDATE products SET brand = N'WD', description = N'TDP: 4W' WHERE id = 422;
UPDATE products SET brand = N'WD', description = N'TDP: 5W' WHERE id = 423;
UPDATE products SET brand = N'WD', description = N'TDP: 5W' WHERE id = 424;
UPDATE products SET brand = N'WD', description = N'TDP: 6W' WHERE id = 425;
UPDATE products SET brand = N'Samsung', description = N'TDP: 4W' WHERE id = 426;
UPDATE products SET brand = N'Samsung', description = N'TDP: 5W' WHERE id = 427;
UPDATE products SET brand = N'SanDisk', description = N'TDP: 5W' WHERE id = 428;
UPDATE products SET brand = N'Seagate', description = N'TDP: 5W' WHERE id = 429;
UPDATE products SET brand = N'Seagate', description = N'TDP: 5W' WHERE id = 430;
UPDATE products SET brand = N'Crucial', description = N'TDP: 4W' WHERE id = 431;
UPDATE products SET brand = N'Crucial', description = N'TDP: 5W' WHERE id = 432;
UPDATE products SET brand = N'Kingston', description = N'TDP: 4W' WHERE id = 433;
UPDATE products SET brand = N'Corsair', description = N'TDP: 12W' WHERE id = 434;
UPDATE products SET brand = N'Corsair', description = N'TDP: 12W' WHERE id = 435;
UPDATE products SET brand = N'NZXT', description = N'TDP: 12W' WHERE id = 436;
UPDATE products SET brand = N'NZXT', description = N'TDP: 15W' WHERE id = 437;
UPDATE products SET brand = N'ASUS', description = N'TDP: 15W' WHERE id = 438;
UPDATE products SET brand = N'ASUS', description = N'TDP: 15W' WHERE id = 439;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 15W' WHERE id = 440;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 15W' WHERE id = 441;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 15W' WHERE id = 442;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 15W' WHERE id = 443;
UPDATE products SET brand = N'MSI', description = N'TDP: 12W' WHERE id = 444;
UPDATE products SET brand = N'ID-COOLING', description = N'TDP: 10W' WHERE id = 445;
UPDATE products SET brand = N'ASUS', description = N'TDP: 450W' WHERE id = 446;
UPDATE products SET brand = N'MSI', description = N'TDP: 320W' WHERE id = 447;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 115W' WHERE id = 448;
UPDATE products SET brand = N'GIGABYTE', description = N'TDP: 70W' WHERE id = 449;
UPDATE products SET brand = N'ASUS', description = N'TDP: 160W' WHERE id = 450;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 170W' WHERE id = 451;
UPDATE products SET brand = N'AMD', description = N'TDP: 165W' WHERE id = 452;
UPDATE products SET brand = N'AMD', description = N'TDP: 132W' WHERE id = 453;
UPDATE products SET brand = N'AMD', description = N'TDP: 263W' WHERE id = 454;
UPDATE products SET brand = N'NVIDIA', description = N'TDP: 75W' WHERE id = 455;
UPDATE products SET brand = N'WD', description = N'TDP: 6W' WHERE id = 456;
UPDATE products SET brand = N'WD', description = N'TDP: 7W' WHERE id = 457;
UPDATE products SET brand = N'WD', description = N'TDP: 8W' WHERE id = 458;
UPDATE products SET brand = N'Seagate', description = N'TDP: 6W' WHERE id = 459;
UPDATE products SET brand = N'Seagate', description = N'TDP: 8W' WHERE id = 460;
UPDATE products SET brand = N'Seagate', description = N'TDP: 9W' WHERE id = 461;
UPDATE products SET brand = N'Seagate', description = N'TDP: 10W' WHERE id = 462;
UPDATE products SET brand = N'WD', description = N'TDP: 9W' WHERE id = 463;
UPDATE products SET brand = N'Seagate', description = N'TDP: 10W' WHERE id = 464;
UPDATE products SET brand = N'WD', description = N'TDP: 10W' WHERE id = 465;
UPDATE products SET brand = N'Toshiba', description = N'TDP: 4W' WHERE id = 466;
UPDATE products SET brand = N'Toshiba', description = N'TDP: 7W' WHERE id = 467;
UPDATE products SET brand = N'WD', description = N'TDP: 4W' WHERE id = 468;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 469;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 470;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 471;
UPDATE products SET brand = N'MSI', description = N'TDP: 0W' WHERE id = 472;
UPDATE products SET brand = N'MSI', description = N'TDP: 0W' WHERE id = 473;
UPDATE products SET brand = N'ASUS', description = N'TDP: 0W' WHERE id = 474;
UPDATE products SET brand = N'ASUS', description = N'TDP: 0W' WHERE id = 475;
UPDATE products SET brand = N'Cooler Master', description = N'TDP: 0W' WHERE id = 476;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 0W' WHERE id = 477;
UPDATE products SET brand = N'ASRock', description = N'TDP: 0W' WHERE id = 478;
UPDATE products SET brand = N'NZXT', description = N'TDP: 0W' WHERE id = 479;
UPDATE products SET brand = N'NZXT', description = N'TDP: 0W' WHERE id = 480;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 0W' WHERE id = 481;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 0W' WHERE id = 482;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 483;
UPDATE products SET brand = N'Corsair', description = N'TDP: 0W' WHERE id = 484;
UPDATE products SET brand = N'MSI', description = N'TDP: 0W' WHERE id = 485;
UPDATE products SET brand = N'Xigmatek', description = N'TDP: 0W' WHERE id = 486;
UPDATE products SET brand = N'Mik', description = N'TDP: 0W' WHERE id = 487;
UPDATE products SET brand = N'SAMA', description = N'TDP: 0W' WHERE id = 488;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 5W' WHERE id = 489;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 5W' WHERE id = 490;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 5W' WHERE id = 491;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 3W' WHERE id = 492;
UPDATE products SET brand = N'Noctua', description = N'TDP: 4W' WHERE id = 493;
UPDATE products SET brand = N'Noctua', description = N'TDP: 3W' WHERE id = 494;
UPDATE products SET brand = N'ID-COOLING', description = N'TDP: 5W' WHERE id = 495;
UPDATE products SET brand = N'ID-COOLING', description = N'TDP: 5W' WHERE id = 496;
UPDATE products SET brand = N'Cooler Master', description = N'TDP: 5W' WHERE id = 497;
UPDATE products SET brand = N'Jonsbo', description = N'TDP: 2W' WHERE id = 498;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 4W' WHERE id = 499;
UPDATE products SET brand = N'Lian Li', description = N'TDP: 3W' WHERE id = 500;
UPDATE products SET brand = N'Corsair', description = N'TDP: 3W' WHERE id = 501;
UPDATE products SET brand = N'Corsair', description = N'TDP: 3W' WHERE id = 502;
UPDATE products SET brand = N'NZXT', description = N'TDP: 3W' WHERE id = 503;
UPDATE products SET brand = N'DeepCool', description = N'TDP: 3W' WHERE id = 504;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 2W' WHERE id = 505;
UPDATE products SET brand = N'Thermalright', description = N'TDP: 2W' WHERE id = 506;
UPDATE products SET brand = N'Montech', description = N'TDP: 2W' WHERE id = 507;
UPDATE products SET brand = N'Xigmatek', description = N'TDP: 2W' WHERE id = 508;
UPDATE products SET brand = N'Mik', description = N'TDP: 2W' WHERE id = 509;
UPDATE products SET brand = N'SAMA', description = N'TDP: 2W' WHERE id = 510;
UPDATE products SET brand = N'Noctua', description = N'TDP: 1W' WHERE id = 511;
UPDATE products SET brand = N'Arctic', description = N'TDP: 1W' WHERE id = 512;
UPDATE products SET brand = N'AKKO', description = N'TDP: 2W' WHERE id = 513;
UPDATE products SET brand = N'AKKO', description = N'TDP: 1W' WHERE id = 514;
UPDATE products SET brand = N'Keychron', description = N'TDP: 2W' WHERE id = 515;
UPDATE products SET brand = N'Keychron', description = N'TDP: 2W' WHERE id = 516;
UPDATE products SET brand = N'Logitech', description = N'TDP: 2W' WHERE id = 517;
UPDATE products SET brand = N'Razer', description = N'TDP: 3W' WHERE id = 518;
UPDATE products SET brand = N'Corsair', description = N'TDP: 2W' WHERE id = 519;
UPDATE products SET brand = N'SteelSeries', description = N'TDP: 2W' WHERE id = 520;
UPDATE products SET brand = N'ASUS', description = N'TDP: 3W' WHERE id = 521;
UPDATE products SET brand = N'Dareu', description = N'TDP: 1W' WHERE id = 522;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W' WHERE id = 523;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W' WHERE id = 524;
UPDATE products SET brand = N'Razer', description = N'TDP: 1W' WHERE id = 525;
UPDATE products SET brand = N'Razer', description = N'TDP: 1W' WHERE id = 526;
UPDATE products SET brand = N'SteelSeries', description = N'TDP: 1W' WHERE id = 527;
UPDATE products SET brand = N'Corsair', description = N'TDP: 1W' WHERE id = 528;
UPDATE products SET brand = N'ASUS', description = N'TDP: 1W' WHERE id = 529;
UPDATE products SET brand = N'Dareu', description = N'TDP: 1W' WHERE id = 530;
UPDATE products SET brand = N'Samsung', description = N'TDP: 1W' WHERE id = 531;
UPDATE products SET brand = N'Antec', description = N'TDP: 1W' WHERE id = 532;
UPDATE products SET brand = N'HyperX', description = N'TDP: 1W' WHERE id = 533;
UPDATE products SET brand = N'HyperX', description = N'TDP: 1W' WHERE id = 534;
UPDATE products SET brand = N'Razer', description = N'TDP: 1W' WHERE id = 535;
UPDATE products SET brand = N'NZXT', description = N'TDP: 2W' WHERE id = 536;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W' WHERE id = 537;
UPDATE products SET brand = N'Logitech', description = N'TDP: 1W' WHERE id = 538;
UPDATE products SET brand = N'SteelSeries', description = N'TDP: 2W' WHERE id = 539;
UPDATE products SET brand = N'Corsair', description = N'TDP: 2W' WHERE id = 540;
UPDATE products SET brand = N'ASUS', description = N'TDP: 2W' WHERE id = 541;
UPDATE products SET brand = N'Dareu', description = N'TDP: 1W' WHERE id = 542;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 543;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W' WHERE id = 544;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W' WHERE id = 545;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 546;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 547;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 548;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W' WHERE id = 549;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W' WHERE id = 550;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 551;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 552;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 553;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W' WHERE id = 554;
UPDATE products SET brand = N'Intel', description = N'TDP: 65W' WHERE id = 555;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 556;
UPDATE products SET brand = N'Intel', description = N'TDP: 125W' WHERE id = 557;
UPDATE products SET brand = N'ASUS', description = N'TDP: 20W' WHERE id = 558;
"""

import re

updates = {}
for line in user_updates_raw.strip().splitlines():
    m = re.search(r"UPDATE products SET brand = N'([^']*)', description = N'([^']*)' WHERE id = (\d+);", line)
    if m:
        brand, desc, pid = m.group(1), m.group(2), int(m.group(3))
        updates[pid] = (brand, desc)

print('Parsed updates count:', len(updates))

with open('d:/Luxury-PC-main/init_luxurypc_full.sql', 'r', encoding='utf-8') as f:
    sql = f.read()

# Let's inspect products in init_luxurypc_full.sql
# We want to see how each line in products is structured:
# (id, name, price, description, image, category_id, stock, created_at, brand)
